#!/usr/bin/env python3
"""Simple Python program with a function that prints Hello 2046."""


def print_hello_2046():
    """Print Hello 2046 and automated program warning to the console."""
    print("Hello 2046")
    print("This greeting is generated by an automated program. Do not reply!")


if __name__ == "__main__":
    print_hello_2046()
